import { StyleProp, TextStyle } from 'react-native'

export const icon-accept:before: StyleProp<TextStyle>
export const icon-activities:before: StyleProp<TextStyle>
export const icon-add-file:before: StyleProp<TextStyle>
export const icon-add-group:before: StyleProp<TextStyle>
export const icon-alarm:before: StyleProp<TextStyle>
export const icon-alert-circle:before: StyleProp<TextStyle>
export const icon-align-justify:before: StyleProp<TextStyle>
export const icon-angle-left:before: StyleProp<TextStyle>
export const icon-announcement-speaker:before: StyleProp<TextStyle>
export const icon-app-outline:before: StyleProp<TextStyle>
export const icon-app:before: StyleProp<TextStyle>
export const icon-arrow-left:before: StyleProp<TextStyle>
export const icon-arrow-right:before: StyleProp<TextStyle>
export const icon-arrow-swap:before: StyleProp<TextStyle>
export const icon-assessment:before: StyleProp<TextStyle>
export const icon-assignment:before: StyleProp<TextStyle>
export const icon-bar-chart-left:before: StyleProp<TextStyle>
export const icon-bar-chart:before: StyleProp<TextStyle>
export const icon-bar-highest:before: StyleProp<TextStyle>
export const icon-bar-lowest:before: StyleProp<TextStyle>
export const icon-bell-fill:before: StyleProp<TextStyle>
export const icon-bell:before: StyleProp<TextStyle>
export const icon-bold:before: StyleProp<TextStyle>
export const icon-book-cover:before: StyleProp<TextStyle>
export const icon-book-pile:before: StyleProp<TextStyle>
export const icon-book-stack:before: StyleProp<TextStyle>
export const icon-book:before: StyleProp<TextStyle>
export const icon-bookmark:before: StyleProp<TextStyle>
export const icon-briefcase:before: StyleProp<TextStyle>
export const icon-business:before: StyleProp<TextStyle>
export const icon-calendar-event:before: StyleProp<TextStyle>
export const icon-calendar:before: StyleProp<TextStyle>
export const icon-callout:before: StyleProp<TextStyle>
export const icon-camera:before: StyleProp<TextStyle>
export const icon-caret-down:before: StyleProp<TextStyle>
export const icon-caret-fill-down:before: StyleProp<TextStyle>
export const icon-caret-fill-left:before: StyleProp<TextStyle>
export const icon-caret-fill-right:before: StyleProp<TextStyle>
export const icon-caret-fill-up:before: StyleProp<TextStyle>
export const icon-caret-left:before: StyleProp<TextStyle>
export const icon-caret-right:before: StyleProp<TextStyle>
export const icon-caret-up:before: StyleProp<TextStyle>
export const icon-chat-card:before: StyleProp<TextStyle>
export const icon-chat:before: StyleProp<TextStyle>
export const icon-chats-circle:before: StyleProp<TextStyle>
export const icon-check-circle:before: StyleProp<TextStyle>
export const icon-checked-fill:before: StyleProp<TextStyle>
export const icon-circle-question-mark:before: StyleProp<TextStyle>
export const icon-classboard:before: StyleProp<TextStyle>
export const icon-clear:before: StyleProp<TextStyle>
export const icon-clock:before: StyleProp<TextStyle>
export const icon-close:before: StyleProp<TextStyle>
export const icon-cloud-arrow-down:before: StyleProp<TextStyle>
export const icon-cloud-download:before: StyleProp<TextStyle>
export const icon-comment-chat:before: StyleProp<TextStyle>
export const icon-commentary:before: StyleProp<TextStyle>
export const icon-community-fill:before: StyleProp<TextStyle>
export const icon-control:before: StyleProp<TextStyle>
export const icon-copy:before: StyleProp<TextStyle>
export const icon-correct:before: StyleProp<TextStyle>
export const icon-credit-card:before: StyleProp<TextStyle>
export const icon-crown:before: StyleProp<TextStyle>
export const icon-curriculum:before: StyleProp<TextStyle>
export const icon-customer-care:before: StyleProp<TextStyle>
export const icon-decline:before: StyleProp<TextStyle>
export const icon-description:before: StyleProp<TextStyle>
export const icon-discount:before: StyleProp<TextStyle>
export const icon-discussion:before: StyleProp<TextStyle>
export const icon-discussions:before: StyleProp<TextStyle>
export const icon-doc:before: StyleProp<TextStyle>
export const icon-docx:before: StyleProp<TextStyle>
export const icon-dotted-roller:before: StyleProp<TextStyle>
export const icon-dotted-spinner:before: StyleProp<TextStyle>
export const icon-double-caret-down:before: StyleProp<TextStyle>
export const icon-double-caret-up:before: StyleProp<TextStyle>
export const icon-download:before: StyleProp<TextStyle>
export const icon-edit-area:before: StyleProp<TextStyle>
export const icon-edit-line:before: StyleProp<TextStyle>
export const icon-edit-pen:before: StyleProp<TextStyle>
export const icon-ellipsis-h:before: StyleProp<TextStyle>
export const icon-ellipsis:before: StyleProp<TextStyle>
export const icon-email:before: StyleProp<TextStyle>
export const icon-empty-trash:before: StyleProp<TextStyle>
export const icon-end-call:before: StyleProp<TextStyle>
export const icon-endorse-check:before: StyleProp<TextStyle>
export const icon-error-alert:before: StyleProp<TextStyle>
export const icon-error-report:before: StyleProp<TextStyle>
export const icon-event-cancel:before: StyleProp<TextStyle>
export const icon-event-schedule:before: StyleProp<TextStyle>
export const icon-external-link:before: StyleProp<TextStyle>
export const icon-eye:before: StyleProp<TextStyle>
export const icon-facebook-fill:before: StyleProp<TextStyle>
export const icon-facebook:before: StyleProp<TextStyle>
export const icon-feeds:before: StyleProp<TextStyle>
export const icon-file-plus:before: StyleProp<TextStyle>
export const icon-file-text:before: StyleProp<TextStyle>
export const icon-file:before: StyleProp<TextStyle>
export const icon-files:before: StyleProp<TextStyle>
export const icon-filter-icon:before: StyleProp<TextStyle>
export const icon-filter-lines:before: StyleProp<TextStyle>
export const icon-flag-fill:before: StyleProp<TextStyle>
export const icon-flag:before: StyleProp<TextStyle>
export const icon-folder:before: StyleProp<TextStyle>
export const icon-formula:before: StyleProp<TextStyle>
export const icon-full-signal:before: StyleProp<TextStyle>
export const icon-gallery:before: StyleProp<TextStyle>
export const icon-game:before: StyleProp<TextStyle>
export const icon-gear-fill-edge:before: StyleProp<TextStyle>
export const icon-gear-fill:before: StyleProp<TextStyle>
export const icon-gear:before: StyleProp<TextStyle>
export const icon-google:before: StyleProp<TextStyle>
export const icon-graduation-cap-outline:before: StyleProp<TextStyle>
export const icon-graduation-cap:before: StyleProp<TextStyle>
export const icon-group-users:before: StyleProp<TextStyle>
export const icon-hamburger:before: StyleProp<TextStyle>
export const icon-help-circle:before: StyleProp<TextStyle>
export const icon-help-file:before: StyleProp<TextStyle>
export const icon-helper:before: StyleProp<TextStyle>
export const icon-hide:before: StyleProp<TextStyle>
export const icon-high-volume:before: StyleProp<TextStyle>
export const icon-image:before: StyleProp<TextStyle>
export const icon-info-circle:before: StyleProp<TextStyle>
export const icon-info-italics:before: StyleProp<TextStyle>
export const icon-info:before: StyleProp<TextStyle>
export const icon-insert-space:before: StyleProp<TextStyle>
export const icon-instagram:before: StyleProp<TextStyle>
export const icon-invitation:before: StyleProp<TextStyle>
export const icon-isers-outline:before: StyleProp<TextStyle>
export const icon-italic:before: StyleProp<TextStyle>
export const icon-jpg:before: StyleProp<TextStyle>
export const icon-library:before: StyleProp<TextStyle>
export const icon-line-dash:before: StyleProp<TextStyle>
export const icon-link:before: StyleProp<TextStyle>
export const icon-linkedin-fill:before: StyleProp<TextStyle>
export const icon-linkedin:before: StyleProp<TextStyle>
export const icon-live-class:before: StyleProp<TextStyle>
export const icon-lock-fill:before: StyleProp<TextStyle>
export const icon-log-out:before: StyleProp<TextStyle>
export const icon-love-outline:before: StyleProp<TextStyle>
export const icon-love:before: StyleProp<TextStyle>
export const icon-low-signal:before: StyleProp<TextStyle>
export const icon-low-volume:before: StyleProp<TextStyle>
export const icon-map-pin-sm:before: StyleProp<TextStyle>
export const icon-map-pin:before: StyleProp<TextStyle>
export const icon-map:before: StyleProp<TextStyle>
export const icon-master-card:before: StyleProp<TextStyle>
export const icon-maximize-arrow:before: StyleProp<TextStyle>
export const icon-maximize:before: StyleProp<TextStyle>
export const icon-members:before: StyleProp<TextStyle>
export const icon-message:before: StyleProp<TextStyle>
export const icon-mic-off:before: StyleProp<TextStyle>
export const icon-mic-on:before: StyleProp<TextStyle>
export const icon-minimize:before: StyleProp<TextStyle>
export const icon-minus:before: StyleProp<TextStyle>
export const icon-motivation:before: StyleProp<TextStyle>
export const icon-mp4:before: StyleProp<TextStyle>
export const icon-music-note:before: StyleProp<TextStyle>
export const icon-mute:before: StyleProp<TextStyle>
export const icon-naira:before: StyleProp<TextStyle>
export const icon-no-photo:before: StyleProp<TextStyle>
export const icon-no-wifi:before: StyleProp<TextStyle>
export const icon-note-text-fill:before: StyleProp<TextStyle>
export const icon-note-text:before: StyleProp<TextStyle>
export const icon-notepad:before: StyleProp<TextStyle>
export const icon-opposite-caret:before: StyleProp<TextStyle>
export const icon-options:before: StyleProp<TextStyle>
export const icon-paper-clip:before: StyleProp<TextStyle>
export const icon-paper-plane-angle:before: StyleProp<TextStyle>
export const icon-paper-plane:before: StyleProp<TextStyle>
export const icon-parent-child:before: StyleProp<TextStyle>
export const icon-parent-group:before: StyleProp<TextStyle>
export const icon-parents:before: StyleProp<TextStyle>
export const icon-paste:before: StyleProp<TextStyle>
export const icon-pause-no-fill:before: StyleProp<TextStyle>
export const icon-pause:before: StyleProp<TextStyle>
export const icon-pdf:before: StyleProp<TextStyle>
export const icon-phone:before: StyleProp<TextStyle>
export const icon-picture-in-picture:before: StyleProp<TextStyle>
export const icon-pie-chart:before: StyleProp<TextStyle>
export const icon-pie:before: StyleProp<TextStyle>
export const icon-play-bg:before: StyleProp<TextStyle>
export const icon-play-outline:before: StyleProp<TextStyle>
export const icon-play-square:before: StyleProp<TextStyle>
export const icon-play:before: StyleProp<TextStyle>
export const icon-plus:before: StyleProp<TextStyle>
export const icon-poll:before: StyleProp<TextStyle>
export const icon-ppt:before: StyleProp<TextStyle>
export const icon-practice-card:before: StyleProp<TextStyle>
export const icon-printer:before: StyleProp<TextStyle>
export const icon-privacy:before: StyleProp<TextStyle>
export const icon-question-hexagon:before: StyleProp<TextStyle>
export const icon-questions:before: StyleProp<TextStyle>
export const icon-reply:before: StyleProp<TextStyle>
export const icon-restart:before: StyleProp<TextStyle>
export const icon-reward-pack:before: StyleProp<TextStyle>
export const icon-school-fill:before: StyleProp<TextStyle>
export const icon-school:before: StyleProp<TextStyle>
export const icon-search:before: StyleProp<TextStyle>
export const icon-select:before: StyleProp<TextStyle>
export const icon-share-fill:before: StyleProp<TextStyle>
export const icon-share-network:before: StyleProp<TextStyle>
export const icon-share-screen:before: StyleProp<TextStyle>
export const icon-share:before: StyleProp<TextStyle>
export const icon-shield-ok:before: StyleProp<TextStyle>
export const icon-show:before: StyleProp<TextStyle>
export const icon-slide:before: StyleProp<TextStyle>
export const icon-sliders:before: StyleProp<TextStyle>
export const icon-smartphone:before: StyleProp<TextStyle>
export const icon-speaker-notes:before: StyleProp<TextStyle>
export const icon-speaker:before: StyleProp<TextStyle>
export const icon-square-grid:before: StyleProp<TextStyle>
export const icon-stamp:before: StyleProp<TextStyle>
export const icon-star-full:before: StyleProp<TextStyle>
export const icon-status-indicator:before: StyleProp<TextStyle>
export const icon-stopwatch:before: StyleProp<TextStyle>
export const icon-student-group:before: StyleProp<TextStyle>
export const icon-student-user:before: StyleProp<TextStyle>
export const icon-student:before: StyleProp<TextStyle>
export const icon-swap:before: StyleProp<TextStyle>
export const icon-tachometer:before: StyleProp<TextStyle>
export const icon-tag-fill:before: StyleProp<TextStyle>
export const icon-tag:before: StyleProp<TextStyle>
export const icon-target:before: StyleProp<TextStyle>
export const icon-teacher-class:before: StyleProp<TextStyle>
export const icon-teacher-talk:before: StyleProp<TextStyle>
export const icon-teacher:before: StyleProp<TextStyle>
export const icon-thumbs-down:before: StyleProp<TextStyle>
export const icon-thumbs-up:before: StyleProp<TextStyle>
export const icon-timeline:before: StyleProp<TextStyle>
export const icon-timer:before: StyleProp<TextStyle>
export const icon-trash:before: StyleProp<TextStyle>
export const icon-trending-down:before: StyleProp<TextStyle>
export const icon-trending-up:before: StyleProp<TextStyle>
export const icon-twitter:before: StyleProp<TextStyle>
export const icon-txt:before: StyleProp<TextStyle>
export const icon-underline:before: StyleProp<TextStyle>
export const icon-upload:before: StyleProp<TextStyle>
export const icon-url-link:before: StyleProp<TextStyle>
export const icon-user-circle-gear:before: StyleProp<TextStyle>
export const icon-user-circle-minus:before: StyleProp<TextStyle>
export const icon-user-circle-plus:before: StyleProp<TextStyle>
export const icon-user-circle:before: StyleProp<TextStyle>
export const icon-user-fill:before: StyleProp<TextStyle>
export const icon-user-outline:before: StyleProp<TextStyle>
export const icon-user-plus:before: StyleProp<TextStyle>
export const icon-verified-note:before: StyleProp<TextStyle>
export const icon-verified-user:before: StyleProp<TextStyle>
export const icon-verve-card:before: StyleProp<TextStyle>
export const icon-video-cam-outline:before: StyleProp<TextStyle>
export const icon-video-card:before: StyleProp<TextStyle>
export const icon-video-off:before: StyleProp<TextStyle>
export const icon-video-on:before: StyleProp<TextStyle>
export const icon-video-show:before: StyleProp<TextStyle>
export const icon-videocam:before: StyleProp<TextStyle>
export const icon-visa-card:before: StyleProp<TextStyle>
export const icon-wallet-fill:before: StyleProp<TextStyle>
export const icon-wallet-outline:before: StyleProp<TextStyle>
export const icon-warning-alert:before: StyleProp<TextStyle>
export const icon-watch:before: StyleProp<TextStyle>
export const icon-whatsapp-fill:before: StyleProp<TextStyle>
export const icon-whatsapp:before: StyleProp<TextStyle>
export const icon-wifi:before: StyleProp<TextStyle>
export const icon-worksheet:before: StyleProp<TextStyle>
export const icon-wrong:before: StyleProp<TextStyle>
export const icon-xls:before: StyleProp<TextStyle>
export const icon-youtube:before: StyleProp<TextStyle>
export const icon-zoom-in:before: StyleProp<TextStyle>
